Restaurant Page
Godswilly/restaurant-page pull request #1
Opened 2021-01-27 13:51 UTC by Godswilly

- Created a restaurant site using Javascript DOM 
- I made use of import and export to call objects
- I Implemented ES6 functions

2021-01-27 15:00 UTC, uche-inyama requested changes
## Changes Required

### Hi @Godswilly  :wave: 

There are some updates to make in your project.

* [ ] Your package.json file is missing a a package: **webpack-dev-server**
* [ ] When I tried to start your application with **npm start**, I had this error below:

                Error: Cannot find module 'webpack-cli/bin/config-yargs' 

#### That's it, rectify the error and update your package.json file; then submit another form for a code review.

### Have a great day :slightly_smiling_face: 

### ``` Uchechukwu Henry Inyama```

2021-01-28 04:12 UTC, peterrobert requested changes
### CHANGES REQUIRED ♻️ 🛑 
Hello, @Godswilly  very nice project. I love the way you have modularised your code. Your work is very impressive 👍🏿 . However, there are a  few changes to be made. Kindly check below ⬇️ 

- [ ]  Files not related to the project example .vscode should be added to the .gitignore and should not be committed. 
- [ ] In your readme file, you have added `npm run watch` this is not configured in your package .json file. Kindly do so.

- [ ]  After running eslint on my machine, there appear to be some errors ⬇️ 
![Screenshot from 2021-01-28 06-58-53](https://user-images.githubusercontent.com/32361963/106088658-6d503280-6137-11eb-9d07-408de89d33e7.png)

kindly fix these errors.

### if you have any questions kindly reach me on slack @peterrobert

### HAPPY CODING 💻

2021-01-28 04:12 UTC, peterrobert commented on dist/index.html
> +  <div id="content">
You have left out  a closing tag for this <div>

2021-01-28 07:32 UTC, mikenath223 approved these changes
### CONGRATULATIONS  👏👏👏

This project meets the requirements for approval.

**STATUS: APPROVED ✅**


Don't forget to fill the project completion form👍
Good luck with the next project.

**HAPPY CODING 🎉💻🎉**

**Michgolden Ukeje (CR)**

2021-03-05 21:13 UTC, merged